In [1]:
import hkvwaporpy as hkv
import pandas as pd
import datetime

https://io.apps.fao.org/gismgr/api/v1/catalog/workspaces/WAPOR/cubes?overview=False

#### METADATA REQUEST FOR AVAILABLE PRODUCTS

In [2]:
# request the catalogus
df = hkv.read_wapor.get_catalogus()
df.head()

,additionalInfo,caption,code,dataType,description,hidden,index,links,operation,tags,workspaceCode
0,"{'format': 'Raster Dataset', 'unit': 'kg/m続 is...",Gross Biomass Water Productivity,L1_GBWP_A,RASTER,The annual Gross Biomass Water Productivity ex...,False,101,"[{'rel': 'self', 'href': 'https://io.apps.fao....","{'pixelTimeSeries': True, 'areaStats': False}","[{'name': 'L1', 'index': 1, 'context': 'LEVELS...",WAPOR
1,"{'format': 'Raster Dataset', 'unit': 'kg/m続 is...",Net Biomass Water Productivity,L1_NBWP_A,RASTER,The annual Net Biomass Water Productivity expr...,False,102,"[{'rel': 'self', 'href': 'https://io.apps.fao....","{'pixelTimeSeries': True, 'areaStats': False}","[{'name': 'L1', 'index': 2, 'context': 'LEVELS...",WAPOR
2,"{'format': 'Raster Dataset', 'unit': 'mm', 'da...",Actual EvapoTranspiration and Interception (An...,L1_AETI_A,RASTER,The actual EvapoTranspiration and Interceptio...,False,103,"[{'rel': 'self', 'href': 'https://io.apps.fao....","{'pixelTimeSeries': True, 'areaStats': False}","[{'name': 'L1', 'index': 3, 'context': 'LEVELS...",WAPOR
3,"{'format': 'Raster Dataset', 'unit': 'mm', 'da...",Actual EvapoTranspiration and Interception (De...,L1_AETI_D,RASTER,The actual EvapoTranspiration and Interception...,False,104,"[{'rel': 'self', 'href': 'https://io.apps.fao....","{'pixelTimeSeries': True, 'areaStats': False}","[{'name': 'L1', 'index': 4, 'context': 'LEVELS...",WAPOR
4,"{'format': 'Raster Dataset', 'unit': 'mm', 'da...",Transpiration (Annual),L1_T_A,RASTER,The Transpiration (T) data component is the ac...,False,105,"[{'rel': 'self', 'href': 'https://io.apps.fao....","{'pixelTimeSeries': True, 'areaStats': False}","[{'name': 'L1', 'index': 5, 'context': 'LEVELS...",WAPOR

In [3]:
# show all codes
df[['caption','code']]

                                              caption            code
0                    Gross Biomass Water Productivity       L1_GBWP_A
1                      Net Biomass Water Productivity       L1_NBWP_A
2   Actual EvapoTranspiration and Interception (An...       L1_AETI_A
3   Actual EvapoTranspiration and Interception (De...       L1_AETI_D
4                              Transpiration (Annual)          L1_T_A
5                                Evaporation (Annual)          L1_E_A
6                               Interception (Annual)          L1_I_A
7                             Transpiration (Dekadal)          L1_T_D
8                               Evaporation (Dekadal)          L1_E_D
9                              Interception (Dekadal)          L1_I_D
10                             Net Primary Production        L1_NPP_D
11                    Above Ground Biomass Production       L1_AGBP_A
12                          Land Cover Classification        L1_LCC_A
13                       Reference EvapoTranspiration        L1_RET_E
14                                      Precipitation        L1_PCP_E
15     Quality Normalized Difference Vegetation Index  L1_QUAL_NDVI_D
16                   Quality Land Surface Temperature   L1_QUAL_LST_D
17  Actual EvapoTranspiration and Interception (An...       L2_AETI_A
18  Actual EvapoTranspiration and Interception (De...       L2_AETI_D
19                             Transpiration (Annual)          L2_T_A

In [4]:
ds_code = 'L1_RET_E'

#ds_code = 'L2_AETI_D'

In [5]:
# get additional info of the dataset given a code and catalogus
cube_info = hkv.read_wapor.get_info_cube(cube_code=ds_code)

In [6]:
df_avail = hkv.read_wapor.get_data_availability(
    cube_info = cube_info, 
    time_range = '[2001-11-01, 2018-08-01]'
    )

data_avail_period: DAY

In [7]:
df_avail.tail()

,date,raster_id,bbox_srid,bbox_value
year,,,,
2018,2018-07-28,L1_RET_180728,EPSG:4326,"[-30.0044643, -39.9953437, 64.9953077, 40.0044..."
2018,2018-07-29,L1_RET_180729,EPSG:4326,"[-30.0044643, -39.9953437, 64.9953077, 40.0044..."
2018,2018-07-30,L1_RET_180730,EPSG:4326,"[-30.0044643, -39.9953437, 64.9953077, 40.0044..."
2018,2018-07-31,L1_RET_180731,EPSG:4326,"[-30.0044643, -39.9953437, 64.9953077, 40.0044..."
2018,2018-08-01,L1_RET_180801,EPSG:4326,"[-30.0044643, -39.9953437, 64.9953077, 40.0044..."

In [8]:
df_locations = hkv.read_wapor.get_locations()
df_locations.head()

     name  code   type                                               bbox
0   Awash  7010  BASIN  [37.9583333333327, 7.89583333333234, 43.320833...
1  Jordan  6006  BASIN  [34.4249999999993, 29.4624999999998, 36.799999...
2  Litani  6002  BASIN  [35.2291666666659, 33.0999999999998, 36.399999...
3   Niger  7002  BASIN  [-11.5874999999999, 4.27083333333253, 15.85833...
4    Nile  7003  BASIN  [23.4458333333329, -4.0291666666674, 39.808333...

In [9]:
location = df_locations.iloc[0]
loc_type = location['type']
loc_code = location['code']
print(loc_type, loc_code, location['name'])

BASIN 7010 Awash

In [10]:
cube_period = df_avail.iloc[0]
raster_id = cube_period['raster_id']
print(raster_id)

L1_RET_090101

In [11]:
cov_url = hkv.read_wapor.get_coverage_url(raster_id, ds_code, loc_type, loc_code)
print(cov_url)

https://io.apps.fao.org/gismgr/api/v1/download/WAPOR?language=en&requestType=mapset_raster&cubeCode=L1_RET_E&rasterId=L1_RET_090101_7010